/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javalabs;

/**
 *
 * @author Максим
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
    }
    
     public static double Calculate(double x) {
        return 1/x;
    }
    
     public static double Result(double a, double b, double h) {
        int n = (int) ((b - a) / h);
        double sum = 0.5 * (Calculate(a) + Calculate(b));
        
        for (int i = 1; i < n; i++) {
            double x = a + i * h;
            sum += Calculate(x);
        }
        
        double lastSegment = (b - (a + n * h));
        sum += lastSegment > 0 ? 0.5 * (Calculate(a + n * h) + Calculate(b)) * lastSegment / h : 0;
        
        return sum * h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();
        addEntryButton = new javax.swing.JButton();
        deleteEntryButton = new javax.swing.JButton();
        getResultButton = new javax.swing.JButton();
        lowerBorderTextField = new javax.swing.JTextField();
        upperBorderTextField = new javax.swing.JTextField();
        stepTextField = new javax.swing.JTextField();
        lowerBorderLabel = new javax.swing.JLabel();
        upperBorderLabel = new javax.swing.JLabel();
        stepLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Вычисление определенного интегралла - 1/x");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(211, 183, 216));

        infoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Нижняя граница", "Верхняя граница", "Шаг", "Результат"
            }
        ));
        jScrollPane2.setViewportView(infoTable);
        if (infoTable.getColumnModel().getColumnCount() > 0) {
            infoTable.getColumnModel().getColumn(0).setHeaderValue("Нижняя граница");
            infoTable.getColumnModel().getColumn(1).setHeaderValue("Верхняя граница");
            infoTable.getColumnModel().getColumn(2).setHeaderValue("Шаг");
            infoTable.getColumnModel().getColumn(3).setHeaderValue("Результат");
        }
        infoTable.getAccessibleContext().setAccessibleDescription("");

        addEntryButton.setBackground(new java.awt.Color(161, 62, 151));
        addEntryButton.setText("Добавить");
        addEntryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEntryButtonMouseClicked(evt);
            }
        });

        deleteEntryButton.setBackground(new java.awt.Color(161, 62, 151));
        deleteEntryButton.setText("Удалить");
        deleteEntryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteEntryButtonMouseClicked(evt);
            }
        });

        getResultButton.setBackground(new java.awt.Color(161, 62, 151));
        getResultButton.setText("Вычислить");
        getResultButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getResultButtonMouseClicked(evt);
            }
        });

        stepTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepTextFieldActionPerformed(evt);
            }
        });

        lowerBorderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lowerBorderLabel.setText(" Нижняя граница");

        upperBorderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upperBorderLabel.setText("Верхняя граница");

        stepLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stepLabel.setText("Шаг");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(upperBorderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lowerBorderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lowerBorderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upperBorderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(getResultButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteEntryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEntryButton)
                    .addComponent(lowerBorderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowerBorderLabel))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteEntryButton)
                    .addComponent(upperBorderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upperBorderLabel))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getResultButton)
                    .addComponent(stepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepLabel))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stepTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stepTextFieldActionPerformed

    private void addEntryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEntryButtonMouseClicked
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)infoTable.getModel();
        
        String temp = lowerBorderTextField.getText();
        if (temp.isEmpty())
            return;
        double low = Double.parseDouble(temp);
        temp = upperBorderTextField.getText();
        if (temp.isEmpty())
            return;
        double high = Double.parseDouble(temp);
        temp = stepTextField.getText();
        if (temp.isEmpty()) return;
        double shift = Double.parseDouble(temp);
        
        model.addRow(new Object[] {low, high, shift, 0});
    }//GEN-LAST:event_addEntryButtonMouseClicked

    private void deleteEntryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEntryButtonMouseClicked
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)infoTable.getModel();
        
        int index = infoTable.getSelectedRow();
        
        if (index == -1) return;
        
        model.removeRow(index);
    }//GEN-LAST:event_deleteEntryButtonMouseClicked

    private void getResultButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getResultButtonMouseClicked
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)infoTable.getModel();
        
        int count = model.getRowCount();
        
        for (int i = 0; i < count; i++) {
            String lowObj = model.getValueAt(i, 0).toString();
            String highObj = model.getValueAt(i, 1).toString();
            String shiftObj = model.getValueAt(i, 2).toString();
            
            double resNum = Result(Double.parseDouble(lowObj),
                    Double.parseDouble(highObj),
                    Double.parseDouble(shiftObj));
            
            Object resObj = resNum;
            model.setValueAt(resObj, i, 3);
        }
    }//GEN-LAST:event_getResultButtonMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEntryButton;
    private javax.swing.JButton deleteEntryButton;
    private javax.swing.JButton getResultButton;
    private javax.swing.JTable infoTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lowerBorderLabel;
    private javax.swing.JTextField lowerBorderTextField;
    private javax.swing.JLabel stepLabel;
    private javax.swing.JTextField stepTextField;
    private javax.swing.JLabel upperBorderLabel;
    private javax.swing.JTextField upperBorderTextField;
    // End of variables declaration//GEN-END:variables
}
